# Generated by Django 2.2 on 2019-06-30 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
